name: cog-kiosk
summary: cog wpewebkit browser
description: cog wpewebkit browser
version: 0.18.4
adopt-info: launcher

base: core24
confinement: strict
grade: stable

platforms:
  amd64:

plugs:
  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
    default-provider: mesa-2404

layout:
  /usr/libexec/wpe-webkit-2.0:
    bind: $SNAP/usr/libexec/wpe-webkit-2.0
  /usr/lib/$CRAFT_ARCH_TRIPLET/wpe-webkit-2.0:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/wpe-webkit-2.0
  /usr/lib/$CRAFT_ARCH_TRIPLET/cog:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/cog
  /usr/share:
    bind: $SNAP/usr/share
  /usr/share/drirc.d:
    bind: $SNAP/gpu-2404/drirc.d
  /usr/share/libdrm:
    bind: $SNAP/gpu-2404/libdrm
  /usr/share/X11:
    bind: $SNAP/gpu-2404/X11
  /etc/fonts:
    bind: $SNAP/etc/fonts

apps:
  daemon:
    command-chain:
      - bin/gpu-2404-wrapper
    command: bin/launch-cog
    daemon: simple
    restart-condition: always
    plugs:
      - audio-playback
      - audio-record
      - network
      - network-bind
      - opengl
      - wayland
    environment:
      XDG_DATA_HOME: ${SNAP_DATA}/usr/share
      XDG_CONFIG_HOME: ${SNAP_DATA}/.config
      XDG_DATA_DIRS: ${SNAP_COMMON}/usr/share:${SNAP}/usr/share:$XDG_DATA_DIRS
      XDG_CONFIG_DIRS: ${SNAP}/etc/xdg:${XDG_CONFIG_DIRS}
      XDG_CACHE_HOME: ${SNAP_COMMON}/.cache
      WPE_SHELL_MEDIA_DISK_CACHE_PATH: ${XDG_CACHE_HOME}
  cog:
    command-chain:
      - bin/gpu-2404-wrapper
    command: bin/launch-cog
    plugs:
      - audio-playback
      - audio-record
      - network
      - network-bind
      - opengl
      - wayland
    environment:
      XDG_DATA_HOME: ${SNAP_USER_DATA}/usr/share
      XDG_CONFIG_HOME: ${SNAP_USER_DATA}/.config
      XDG_DATA_DIRS: ${SNAP_USER_COMMON}/usr/share:${SNAP}/usr/share:${XDG_DATA_DIRS}
      XDG_CONFIG_DIRS: ${SNAP}/etc/xdg:$XDG_CONFIG_DIRS
      XDG_CACHE_HOME: ${SNAP_USER_COMMON}/.cache
      WPE_SHELL_MEDIA_DISK_CACHE_PATH: ${XDG_CACHE_HOME}
  cogctl:
    command: usr/bin/cogctl

parts:
  libwpe:
    source: https://wpewebkit.org/releases/libwpe-1.16.2.tar.xz
    plugin: meson
    meson-parameters:
      - --buildtype=release
      - --prefix=/usr
    build-packages:
      - libegl-dev
      - libxkbcommon-dev
      - meson
      - pkg-config
    stage-packages:
      - libxkbcommon0
  wpebackend-fdo:
    after: [libwpe]
    source: https://wpewebkit.org/releases/wpebackend-fdo-1.16.0.tar.xz
    plugin: meson
    meson-parameters:
      - --buildtype=release
      - --prefix=/usr
    build-packages:
      - libepoxy-dev
      - libglib2.0-dev
      - libwayland-bin
      - libwayland-dev
    stage-packages:
      - libepoxy0
      - libglib2.0-0
      - libwayland-client0
      - libwayland-egl1
  wpewebkit:
    after: [libwpe, wpebackend-fdo]
    source: https://wpewebkit.org/releases/wpewebkit-2.48.1.tar.xz
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - -DPORT=WPE
      - -DCMAKE_INSTALL_PREFIX:PATH=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DENABLE_DOCUMENTATION=OFF
      - -DENABLE_INTROSPECTION=OFF
      - -DENABLE_BUBBLEWRAP_SANDBOX=OFF
      - -DUSE_LIBBACKTRACE=OFF
    build-packages:
      - flite1-dev
      - gperf
      - libatk-bridge2.0-dev
      - libatk1.0-dev
      - libavif-dev
      - libdrm-dev
      - libfontconfig-dev
      - libgbm-dev
      - libgcrypt20-dev
      - libgstreamer-plugins-bad1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-good1.0-dev
      - libharfbuzz-dev
      - libjpeg8-dev
      - libjxl-dev
      - libsoup-3.0-dev
      - libsqlite3-dev
      - libsystemd-dev
      - libtasn1-6-dev
      - libwayland-bin
      - libwayland-dev
      - libwebp-dev
      - libwoff-dev
      - libxml2-dev
      - libxslt1-dev
      - ruby-dev
      - unifdef
      - wayland-protocols
    stage-packages:
      - gstreamer1.0-gl
      - gstreamer1.0-libav
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-base-apps
      - gstreamer1.0-plugins-good
      - libatk-bridge2.0-0t64
      - libatk1.0-0
      - libavif16
      - libflite1
      - libgbm1
      - libgcrypt20
      - libgstreamer-gl1.0-0
      - libharfbuzz-icu0
      - libharfbuzz0b
      - libjpeg8
      - libjxl0.7
      - libsoup-3.0-0
      - libsqlite3-0
      - libsystemd0
      - libtasn1-6
      - libwebp7
      - libwebpdemux2
      - libwoff1
      - libxml2
      - libxslt1.1
  cog:
    after: [wpewebkit]
    source: https://wpewebkit.org/releases/cog-0.18.4.tar.xz
    plugin: meson
    meson-parameters:
      - --buildtype=release
      - --prefix=/usr
      - -Dcog_dbus_control=system
    build-packages:
      - libcairo2-dev
      - libmanette-0.2-dev
      - libinput-dev
    stage-packages:
      - fonts-droid-fallback
      - libatomic1
      - libmanette-0.2-0
      - libinput10
    override-prime: |
      craftctl default
      ln -s libWPEBackend-fdo-1.0.so ${CRAFT_PRIME}/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libWPEBackend-default.so
  gpu-2404:
    after: [cog]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
      - bin/gpu-2404-wrapper
  launcher:
    plugin: dump
    source: launcher
    override-stage: |
      craftctl default
      craftctl set version="$(craftctl get version)-$(git rev-parse --short HEAD)"
