#!/bin/sh -e
snapctl set \
	platform="wl" \
	url="http://localhost:9400" \
	devmode="false" \
	debug="false" \
	error-to-console="false" \
	bgcolor="black" \
	inspector-server-port=9080 \
	inspector-http-server-port=9090

